### Obtain access token
POST {{url}}/public/token
Content-Type: application/json

{
  "username": "whsv26@gmail.com",
  "password": "123456"
}

> {% client.global.set("token", response.headers.valueOf("Authorization")); %}

### Register
POST {{url}}/public/register
Content-Type: application/json

{
  "username": "whsv26@gmail.com",
  "password": "123456",
  "rePassword": "123456"
}

### Update user
PATCH {{url}}/users
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "username": "whsv26@gmail.com",
  "password": "123456"
}

### Refresh FCM token
PUT {{url}}/fcm/refresh
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "fcmToken": "testfcmtoken1"
}
